version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messenger
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
